ilma/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'review'
urlpatterns = [
    path('', rev, name='rev'),
    #path('add_review/', add_review, name='add_review'),
    path('create_rev/', create_rev, name='create_rev')
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('review/', include('ilma.urls')),
    path('contractor/', include('steven.urls')),
    path('request/', include('dana.urls')),
    path('', include('rara.urls')),
]

ilma/models.py
from django.db import models
import datetime

# Create your models here.

RATE=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]

class Review(models.Model):
	#date = models.DateTimeField(auto_now_add=True)
	name = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	rate = models.CharField(max_length=50, choices=RATE)
	comment = models.TextField()

ilma/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm

class ReviewForm(ModelForm):
    class Meta:
        model= Review
        fields = ['name', 'email', 'rate', 'comment']
        labels = {
            'name': 'Name','email':'Email', 'rate':'Rate', 'comment':'Comment',
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'What\'s your name?'}),
            'email' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'email',
                                        'placeholder' : 'What\'s your email?'}),
            'rate' : forms.Select(attrs={'class': 'form-control'}),
            'comment' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'textarea', 'rows' : '3'}),
        }

ilma/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ReviewForm
from .models import Review
import datetime

def rev(request):
	data = Review.objects.all()
	form = ReviewForm(request.POST)
	content = {'form' : form, 'data' : data}
	return render(request, 'review.html', content)

# def add_review(request):
# 	if request.method == 'POST':
# 		form = ReviewForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 			return redirect('/review/')
# 	else:
# 		return redirect('/review/')
		
response_data = []
def create_rev(request):
	if request.method == 'POST':
		print(request.POST)
		name = request.POST.get('name')
		rate = request.POST.get('rate')
		email = request.POST.get('email')
		comment = request.POST.get('comment')

		form = ReviewForm(request.POST)
		if form.is_valid():
			form.save()
			print(name)
			#post = Review(name=name, email=email, rate=rate, comment=comment)

			response_data.append({"name": name, "rate": rate, "comment":comment})

			return HttpResponse(json.dumps(response_data), content_type="application/json")
		return HttpResponse([])

ilma/templates/review.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Review Page
{% endblock %}

{% block style %} <link rel="stylesheet" href="{% static 'css/styles.css' %}" > 
{% endblock %}


{% block content%}
<div class= "rev-container">
	<br><br><br>
		{% if user.is_authenticated %}
			<div class="row" style="color: white; font-family:'Varela Round', sans-serif; font-size: 20px">
			    <div class="col-sm-8" style="padding: 20px 20px 20px 50px">
			    	<p style="font-size: 25px"><b>Please help us to provide you a <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)"> better service </span> </b></p>
			    <!-- 	{% url 'review:create_rev' %} -->
			    	<form method="POST" action="" id="rev-form">
						{% csrf_token %}
					  <div class="form-group row">
					    <label for="name" class="col-sm-2 col-form-label">{{ form.name.label_tag }}</label>
					    <div class="col-sm-10" id="form-name">
					      {{ form.name }}
					    </div>
					  </div>
					  <div class="form-group row">
					    <label for="inputEmail3" class="col-sm-2 col-form-label">{{ form.email.label_tag }}</label>
					    <div class="col-sm-10" id="form-email">
					      {{ form.email }}
					    </div>
					  </div>
					  <div class="form-group row">
					    <label for="rate" class="col-sm-2 col-form-label">{{ form.rate.label_tag }}</label>
					    <div class="col-sm-10" id="form-rate">
					      {{ form.rate }}
					    </div>
					  </div>

					  <div class="form-group">
					    <label for="exampleFormControlTextarea1">{{ form.comment.label_tag }}</label>
					    <div id="form comment">
					    	  {{ form.comment }}
					    </div>
					  </div>
					  <div class="form-group row">
					    <div class="col-sm-10">
					      <button type="submit" class="btn btn-primary" id="but-submit">Submit</button>
					    </div>
					  </div>
					</form>
			    </div>
			    <div class="col-sm-4">
			    <img src="{% static 'img/popup.png' %}" style="max-width:100%; height: auto">
				</div>
			</div>
			<hr style="border: 2px solid white; margin-right: 50px; margin-left: 50px">
		{% else %}
			<p style="font-size: 25px; color: white; font-family:'Varela Round', sans-serif;"><b>Want to write a review? <a href="\accounts" style="color: #fe5b46">Register First</a></b></p>
		{% endif %}

		<div class="list-group" style="padding: 40px 100px 30px 100px">
        	 <p style="color: white; font-family:'Varela Round', sans-serif; font-size: 30px"><b><span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)">Thought</span> on Us</b></p>
        	{% for db in data %}
        		<div style="background-color: #ffafaf; padding: 30px; word-wrap: break-word; color: white; font-family:'Varela Round', sans-serif;" id="kotak-rev">
			  		<h4 class="mb-1"><b>{{ db.name }}</b></h4>
			  		<div class="d-flex w-100 justify-content-between">
			  			<p class="mb-1">{{ db.rate }}/5</p>
			  			<small class="text-muted">{{ db.date }}</small>
			  		</div>
			  		<p class="mb-1">{{ db.comment }}</p>
		  		</div>
		  		<br>
		  	{% endfor %}
		</div>
	</div>
	<br>
	<br>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="{% static 'js/script.js' %}"></script> 

{% endblock %}