steven/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'steven'
urlpatterns = [
    path('', project, name='project'),
    path('save_project/', save_project, name='save_project'),
    path('rq_delete/<id>', rq_delete, name='rq_delete'),
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('review/', include('ilma.urls')),
    path('contractor/', include('steven.urls')),
    path('request/', include('dana.urls')),
    path('', include('rara.urls')),
]

steven/models.py
# Create your models here.
from django.db import models
import datetime

class Contractor(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    project = models.CharField(max_length=50)
    link = models.CharField(max_length=50)
    detail = models.TextField()

steven/forms.py
from django import forms
from .models import Contractor
from django.forms import ModelForm

class ProjectForm(ModelForm):
    class Meta:
        model= Contractor
        fields = ['name', 'email', 'project', 'link', 'detail']
        labels = {
            'name': 'Contractor Name','email':'Email', 'project':'Project', 'link':'Link', 'detail': 'Detail Project'
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Contractor Name', 'id':'name'}),
            'email' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'email',
                                        'placeholder' : 'Contractor\'s email?', 'id':'email'}),
            'project' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'What\'s project?', 'id':'project'}),
            'link' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'What\'s your drive link?', 'id':'link'}),
            'detail' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'textarea', 'rows' : '3', 'placeholder' : 'Describe your project', 'id':'detail'}),
        }

steven/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .forms import ProjectForm
from .models import Contractor
from dana.models import Request

# Create your views here
def project(request):
    data = Request.objects.all()
    form = ProjectForm(request.POST)
    content = {'form' : form, 'data' : data}
    return render(request, 'steven.html', content)

def save_project(request):
	if request.method == 'POST':
		form = ProjectForm(request.POST)
		if form.is_valid():
			form.save()
			return JsonResponse({'success':True, 'message':'Form has been saved!'}, status=200)
	else:
		return render(request, 'steven.html')

def rq_delete(request,id):
    rq = Request.objects.filter(id=id)
    rq.delete()
    return redirect('steven:project')

steven/templates/steven.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Review Page
{% endblock %}

{% block content%}
<style>
    .rev-container{
        background-color :#60BBB6;
    }

    body{
        background-color:#60BBB6;
    }

    #map{
        height:400px;
        width:50%;
        margin-left: 10%;
    }

	.switch {
        cursor: pointer;
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc !important;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white !important;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked+.slider {
        background-color: #9e2222 !important;
    }

    input:focus+.slider {
        box-shadow: 0 0 1px #9e2222 !important;
    }

    input:checked+.slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
</style>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBt_zWzVd_ZQ4Rl3CLZQg0_ObXw20OsEpA&callback=initMap"
async defer></script>
<script src="{% static 'steven.js' %}"></script>

<div class= "rev-container" style="font-family: 'Varela Round', sans-serif; color: black;">
    <br><br><br>
    <div class="list-group" style="padding: 40px 100px 30px 100px">
        <p style="color: white; font-family:'Varela Round', sans-serif; font-size: 30px"><b>Available <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)">Project</span></b></p>
        {% for db in data %}
            <div style="background-color: #ffafaf; padding: 30px; word-wrap: break-word;">
                    <h4 class="mb-1"><b>{{ db.name }}</b></h4>

                    <div class="d-flex w-100 justify-content-between">
                        <p class="mb-1">{{ db.email }}</p>
                        <small class="text-muted" style="font-size: 1.2rem;">{{ db.date }}</small>
                    </div>
                    <div class="d-flex w-100 justify-content-between">
                        <p class="mb-1">{{ db.wideScale }}</p>
			  		</div>
                    <p class="mb-1">{{ db.budget }}</p>
                    <p class="mb-1">{{ db.detail }}</p>
                    <div class="offset-10">
                        <a href="{% url 'steven:rq_delete' id=db.id %}" class="btn btn-primary"><button type="button" class="btn btn-primary"> Do_Project </button></a>
                    </div>
            </div>
            <br>
        {% endfor %}
    </div>

    <hr style="border: 2px solid white; margin-right: 50px; margin-left: 50px">

    <div class="form-request">
        <div class="row">
            <div class = "col sm-2">
                <img src="{% static 'img/kiri.png' %}" style="max-width:100%; height: auto">
            </div>
            <div class="col-sm-8" style="padding: 20px 20px 20px 50px">
                <label class='switch mr-3 col'>
                    <input type='checkbox' id="toggle">
                    <span class="slider round"></span>
                </label>
                <p style="text-align : center; font-size: 30px"><b>Please <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)"> fill</span> the form to </b></p>
                <p style="text-align : center; font-size: 30px;"><b>to take a <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)">Project</span></b></p>
                <p style="text-align : center;">Hello Contractors!! You can check available project above and click "Do_Project" after that fill this form based on your project</p>
            </div>
            <div class = "col sm-2">
                <img src="{% static 'img/kanan.png' %}" style="max-width:80%; height: auto">
            </div>


            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-6" style="padding: 20px 20px 20px 50px">
                        <form method="POST" id="user_form"></form>
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">{{ form.name.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.name }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="inputEmail3" class="col-sm-2 col-form-label">{{ form.email.label_tag }}</label>
                                <div class="col-sm-10">
                                {{ form.email }}
                                </div>
                            </div>
                    </div>

                    <div class="col-sm-6" style="padding: 20px 20px 20px 50px">
                        <div class="form-group row">
                            <label for="wideScale" class="col-sm-2 col-form-label">{{ form.project.label_tag }}</label>
                            <div class="col-sm-10">
                                {{ form.project }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="budget" class="col-sm-2 col-form-label">{{ form.link.label_tag }}</label>
                            <div class="col-sm-10">
                                {{ form.link }}
                                <small>submit your project design and other file drive link</small>
                            </div>
                        </div>
                    </div>
                </div>

                    <div class="form-group" style="padding-left: 35px">
                            <label for="exampleFormControlTextarea1" >{{ form.detail.label_tag }}</label><br>
                            <small>Describe your work in project and tell what have you done</small>
                            {{ form.detail }}
                    </div>
                    <br>
                    <p style="padding-left: 35px;">Location:</p>
                    <br>
                    <div id="map"></div>
                    <br><br>
                    <div class="form-group row">
                        <div class="col-sm-6 offset-6 center">
                            <button  class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <br><br><br>
</div>
{% endblock %}