dana/urls.py
from . import views
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'dana'
urlpatterns = [
    path('', req, name='req'),
    path('add_request/', add_request, name='add_request'),
    path('rq_delete/<id>', views.rq_delete, name='rq_delete'),
    path('ganti_nama/', views.ganti_nama, name='ganti_nama')
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('review/', include('ilma.urls')),
    path('contractor/', include('steven.urls')),
    path('request/', include('dana.urls')),
    path('', include('rara.urls')),
]

dana/models.py
from django.db import models
import datetime

# Create your models here.

#RATE=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
RANGE =[('100-300 M','100-300 M'),('301-500 M','301-500 M'),('501-1000 M','501-1000 M'),('1001-2000 M','1001-2000 M'),('2001++ M','2001++ M')]

class Request(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    wideScale = models.CharField(max_length=50)
    budget = models.CharField(max_length=50, choices=RANGE)
    detail = models.TextField()

dana/forms.py
from django import forms
from .models import Request
from django.forms import ModelForm

class RequestForm(ModelForm):
    class Meta:
        model= Request
        fields = ['name', 'email', 'wideScale', 'budget','detail']
        labels = {'name': 'Name','email':'Email', 'wideScale':'Wide-Scale', 'budget':'Budget', 'detail':'Detail'}
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'What\'s your name?'}),
            'email' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'email',
                                        'placeholder' : 'What\'s your email?'}),
            'wideScale' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'How big is the Area? (ex : 100 m2)'}),                           
            'budget' : forms.Select(attrs={'class': 'form-control'}),
            'detail' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'textarea', 'rows' : '3'}),
        }

dana/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .forms import RequestForm
from .models import Request
from steven.models import Contractor
import datetime
import json

def req(request):
	data = Contractor.objects.all()
	form = RequestForm(request.POST)
	content = {'form' : form, 'data' : data}
	return render(request, 'request.html', content)

def add_request(request):
	if request.method == 'POST':
		form = RequestForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/request/')
	else:
		return redirect('/request/')


def rq_delete(request, id):
    rq = Contractor.objects.filter(id=id)
    rq.delete()
    return redirect('dana:req')
    
def ganti_nama(request):
    response = {}
    nama = request.POST["nama"]
    response['nama'] = nama
    return JsonResponse(response)
        

dana/templates/request.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Request Page
{% endblock %}



{% block content%}
<style>
	body{background :#6cc8a3
	}

	.switch {
    cursor: pointer;
    position: relative;
    display: inline-block;
    width: 60px;
    height: 34px;
}

.switch input {
    opacity: 0;
    width: 0;
    height: 0;
}

.slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc !important;
    -webkit-transition: .4s;
    transition: .4s;
}

.slider:before {
    position: absolute;
    content: "";
    height: 26px;
    width: 26px;
    left: 4px;
    bottom: 4px;
    background-color: white !important;
    -webkit-transition: .4s;
    transition: .4s;
}

input:checked+.slider {
    background-color: #9e2222 !important;
}

input:focus+.slider {
    box-shadow: 0 0 1px #9e2222 !important;
}

input:checked+.slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
}

.slider.round {
    border-radius: 34px;
}

.slider.round:before {
    border-radius: 50%;
}


</style>

<div class= "rev-container">
	<br><br><br>
	<div class="form-request">
		<div class="row">
			<div class = "col sm-2">
				<img src="{% static 'img/kiri.png' %}" style="max-width:100%; height: auto">
			</div>
			<div class="col-sm-8" style="padding: 20px 20px 20px 50px">
				<p style="text-align : center; font-size: 25px; font-weight : bold">{% if user.is_authenticated %} Hello {{user.get_username}}{% endif %}</p>
				<div class="mb-5 mx-5 py-2 flex-center-col align-c" style = "margin-bottom : 30px;">
				    <h1 class="text-36 mb-3 d-flex justify-content-center" style = "font-size : 25px;">Apakah kamu ingin mengganti namamu? Jika iya,</h1>
				    <form class="form-inline mb-2 d-flex justify-content-center" method="POST" action='' id="form-nama">
								{%csrf_token%}
				        <input class="form-control searchbox " type="search" placeholder="Ketikkan Namamu" aria-label="Search" name="input_nama">
				        <button class="btn btn-outline-success my-2 my-sm-0 btn-search"  type="submit">Submit</button>
				    </form>
				</div>
				<div class="text-center font-weight-bold">
					<p id="input_nama"  style = "font-size: 50 px"></p>
				</div>
				<p style="text-align : center; font-size: 25px"><b>Please <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)"> fill </span> the form to </b></p>
				<p style="text-align : center; font-size: 25px; color:  #fe5b46; background-color: rgba(255,255,255,0.5)"><b>to Make a Request </b></p>
			</div>
			<div class = "col sm-2">
				<img src="{% static 'img/kanan.png' %}" style="max-width:100%; height: auto">
			</div>

			<div class="col-sm-12 d-flex justify-content-center" style="margin-bottom : 50px">
		 <div class="accordion d-flex" >
					 <div>
							 <a class="title text-light ac-i bg-dark" style = "background:white;cursor: pointer;  padding: 18px; border-radius: 10px; border: none; margin-bottom: 1vh;">Tata Cara Request Project</a>
							 <div class="konten" style="background:#fe9c8f; padding: 10px;border-radius: 10px;overflow: hidden">
										 <ul>
												 <li style="color : black">Isi Form</li>
												 <li style="color : black">Beri Waktu</li>
												 <li style="color : black">Cek "Projects Done"</li>
												 <li style="color : black">Bila ada nama anda</li>
												 <li style="color : black">Berarti project selesai</li>
										 </ul>
								 </div>
					 </div>


					 <div>
							 <a class="title text-light ac-i bg-dark" style = "cursor: pointer;  padding: 18px; border-radius: 10px; border: none; margin-bottom: 1vh">Website Referensi Desain</a>
							 <div class="konten" style="background:#fdf498; padding: 10px;border-radius: 10px;overflow: hidden">
										 <ul>
												 <li style="color : black">Home and Décor</li>
												 <li style="color : black">Small House Bliss</li>
												 <li style="color : black">House Beautiful</li>
												 <li style="color : black">Elle Decor</li>
												 <li style="color : black">IKEA Share Space</li>
										 </ul>
								 </div>
					 </div>

					 <div>
							 <a class="title text-light ac-i bg-dark" style = "cursor: pointer;  padding: 18px; border-radius: 10px; border: none; margin-bottom: 1vh">Tips Mendesain Rumah</a>
							 <div class="konten" style="background:#83d0c9; padding: 10px;border-radius: 10px;overflow: hidden">
										 <ul>
												 <li style="color : black">Tentukan tema,</li>
												 <li style="color : black">Palet warna</li>
												 <li style="color : black">Sesuaikan Budget</li>
												 <li style="color : black">Lihat Referensi</li>
												 <li style="color : black">Konsultasikan</li>
										 </ul>
								 </div>
					 </div>

			 	 </div>
			 </div>


				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-6" style="padding: 20px 20px 20px 50px">
							<form method="POST" action="{% url 'dana:add_request' %}">
							{% csrf_token %}
							<div class="form-group row">
						    <label for="name" class="col-sm-2 col-form-label">{{ form.name.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.name }}
						    </div>
						  </div>

							<div class="form-group row">
						    <label for="inputEmail3" class="col-sm-2 col-form-label">{{ form.email.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.email }}
						    </div>
						  </div>
						</div>

						<div class="col-sm-6" style="padding: 20px 20px 20px 50px">
							<div class="form-group row">
						    <label for="wideScale" class="col-sm-2 col-form-label">{{ form.wideScale.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.wideScale }}
						    </div>
						  </div>

							<div class="form-group row">
						    <label for="budget" class="col-sm-2 col-form-label">{{ form.budget.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.budget }}
						    </div>
						  </div>

						</div>

						</div>

						<div class="form-group">
							<div class="row">
					    <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">{{ form.detail.label_tag }}</label>
							<div class="col-sm-10">
							{{ form.detail }}
							</div>
							</div>
					  </div>

						<div class="form-group row">
					    <div class="col-sm-6 offset-6 center">
					      <button type="submit" class="btn btn-primary">Submit</button>
							</div>
					  </div>

						<div class="col-sm-6 offset-6 center" style="margin-bottom : 50px; margin-top:50px">
							<input id="abab" type="button" value="ada easter egg nih!" style="font-size:10px">
							<label class='switch mr-3'>
                <input type='checkbox' id="toggle">
                <span class="slider round"></span>
              </label>
							</div>



				</div>

			</div>
		<hr style="border: 2px solid white; margin-right: 50px; margin-left: 50px">

		<div class="list-group" style="padding: 40px 100px 30px 100px">
        	 <p style="color: white; font-family:'Varela Round', sans-serif; font-size: 30px"><b><span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)">Projects</span> Done</b></p>
        	{% for db in data %}
        		<div style="background-color: #ffafaf; padding: 30px; word-wrap : break-word">
			  		<h4 class="mb-1"><b>{{ db.name }}</b></h4>
			  		<small class="text-muted">{{ db.date }}</small>
						<p class="mb-1">{{ db.email }}</p>
						<p class="mb-1">{{ db.project }}</p>
						<p class="mb-1">{{ db.link }}</p>
			  		<p class="mb-1">{{ db.detail }}</p>
						<div class="offset-10 center">
							<a href="{% url 'dana:rq_delete' id=db.id %}" class="btn btn-primary"<button>Delete</button></a>
						</div>
		  		</div>
					<!-- kjdkwkjd -->
		  		<br>
		  	{% endfor %}
		</div>
	</div>
	<br>
	<br>
</div>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}