accounts/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('', index_acc, name='index'),
    path('signup/', signup, name='signup'),
    path('login/', index_login, name='in'),
    path('authlogin/', auth_login, name='login'),
    path('logout/', logoutView, name='logout')
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('review/', include('ilma.urls')),
    path('contractor/', include('steven.urls')),
    path('request/', include('dana.urls')),
    path('', include('rara.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length = 50)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
	ROLES = [('Client', 'Client'), ('Contractor', 'Contractor')]
	first_name = forms.CharField(max_length=50)
	last_name = forms.CharField(max_length=50)
	email = forms.EmailField(max_length=50)
	role = forms.CharField(widget=forms.Select(choices=ROLES))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'role', 'password1', 'password2', )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm

def index_acc(request):
	form = SignUpForm()
	return render(request, 'acc.html', {'form' : form})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  
            user.profile.role = form.cleaned_data.get('role')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'acc.html', {'form': form})

def index_login(request):
    form = SignUpForm()
    return render(request, 'acc_login.html')

def auth_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username , password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
    return redirect('/accounts/login')

@login_required
def logoutView(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            logout(request)
    return redirect('/')

accounts/templates/acc.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
 Accounts
{% endblock %}

{% block style %}
<style type="text/css">
  .helptext{
    font-size: 12px;
    color: white;
  }
  ul{
    display: none;
  }

  .errorlist{
    font-size: 12px;
    display: block;
    color: red;

  }

</style>
{% endblock %}

{% block content %}
        <div style="background-color: #6cc8a3; color: white; padding-left: 5%; padding-right: 5%">
        	<br><br><br><br>
        	 <form method="POST" action="{% url 'accounts:signup' %}">
	          {% csrf_token %}
	          {{ form.as_p }}
	          <button type="submit" class="btn btn-primary btn-sm" id="signup-but">Sign Up</button>
	        </form>
	        <p>Already have an account? <a href="/accounts/login/">LOGIN</a></p>
        </div>
      
{% endblock %}

accounts/templates/acc_login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
 Accounts
{% endblock %}

{% block style %}
<style type="text/css">
  .helptext{
    font-size: 12px;
    color: grey;
  }
  ul{
    display: none;
  }

  .errorlist{
    font-size: 12px;
    display: block;
    color: red;

  }

</style>
{% endblock %}


{% block content %}
        <div style="background-color: #6cc8a3; color: white; padding-left: 5%; padding-right: 5%">
          <br><br><br><br>
          <form method="POST" action="{% url 'accounts:login' %}" id="form-login">
          {% csrf_token %}
            <div class="row">
              <div class="col-sm-1"><label> Username </label></div>
              <div class="col-sm-1"></div>
              <div class="col-sm-3">
                <input type="text" name="username" id="username_login" required autocomplete="off"/>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-1"><label> Password </label></div>
              <div class="col-sm-1"></div>
              <div class="col-sm-3">
                <input type="password" name="password" id="password_login" required autocomplete="off"/>
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-sm" id="login-but">Login</button><br>
        </form>
        <p>No account? <a href="/accounts/">Create One</a></p>
        </div>
        
{% endblock %}